call plug#begin()
""" general vim-niceness plugins
Plug 'airblade/vim-rooter'
Plug 'altercation/vim-colors-solarized'
Plug 'bling/vim-airline'
Plug 'edkolev/tmuxline.vim' " further configuration required
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-sensible' 
Plug 'ctrlpvim/ctrlp.vim'
""" syntax/completion plugins
Plug 'Valloric/YouCompleteMe'
Plug 'scrooloose/syntastic'
""" git plugins
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
Plug 'airblade/vim-gitgutter'
""" editting plugins
Plug 'tpope/vim-commentary' " gcc v-gc
Plug 'tpope/vim-surround' " csFT (From/To)
"""golang plugins
Plug 'fatih/vim-go' " further configuration might be needed.
Plug 'nsf/gocode' " have to go setup the filesystem stuff.
"""javascript/web development plugins
Plug 'jelera/vim-javascript-syntax'
Plug 'leshill/vim-json'
Plug 'moll/vim-node'
Plug 'mxw/vim-jsx'
Plug 'othree/html5.vim'
Plug 'pangloss/vim-javascript'
"""clojure
Plug 'tpope/vim-fireplace'
Plug 'kien/rainbow_parentheses.vim'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'guns/vim-sexp'
Plug 'guns/vim-clojure-static'

call plug#end()

""" map leader to space
let mapleader = "\<Space>"
let maplocalleader = "\<Space>"

filetype plugin indent on

""" tab/indentation settings
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set omnifunc=syntaxcomplete#Complete

""" view settings
set t_Co=256
set scrolloff=5
set sidescrolloff=5
set encoding=utf-8
set listchars=tab:▸\ ,eol:¬,trail:·
" toggle showing listchars
nmap <leader>l :set list!<CR>
" extend syntax highlighting to 6000
set smc=6000
set number
set relativenumber

""" solarized settings
syntax enable
set background=dark
colorscheme solarized

""" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

""" timeout settings
set timeoutlen=1000 
set ttimeoutlen=0

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height=5

" jsx settings
let g:jsx_ext_required = 0

" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set laststatus=2

let g:syntastic_javascript_checkers = ['eslint']

" key bindings
" nnoremap <Leader>w :w<CR>
" nnoremap <Leader>] :bnext<CR>
" nnoremap <Leader>[ :bprev<CR>

" tmux navigator settings
let g:tmux_navigator_no_mappings = 0
nnoremap <silent> {Left-mapping} :TmuxNavigateLeft<cr>
nnoremap <silent> {Down-Mapping} :TmuxNavigateDown<cr>
nnoremap <silent> {Up-Mapping} :TmuxNavigateUp<cr>
nnoremap <silent> {Right-Mapping} :TmuxNavigateRight<cr>
nnoremap <silent> {Previous-Mapping} :TmuxNavigatePrevious<cr>

" remove ex-mode
nnoremap Q <nop>

set noswapfile

let g:rbpt_colorpairs = [
\ [ '13', '#6c71c4'],
\ [ '5', '#d33682'],
\ [ '1', '#dc322f'],
\ [ '9', '#cb4b16'],
\ [ '3', '#b58900'],
\ [ '2', '#859900'],
\ [ '6', '#2aa198'],
\ [ '4', '#268bd2'],
\ ]

augroup rainbow_parentheses
au!
au VimEnter * RainbowParenthesesActivate
au BufEnter * RainbowParenthesesLoadRound
au BufEnter * RainbowParenthesesLoadSquare
au BufEnter * RainbowParenthesesLoadBraces
augroup END

set guifont=Meslo\ LG\ S\ DZ\ Regular\ for\ Powerline:h14 

let g:ctrlp_open_new_file = 'r'
let g:ctrlp_open_multiple_files = 'i'
